default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: maji_marriage_development

test:
  <<: *default
  database: maji_marriage_test

production:
  <<: *default
  database: maji_marriage_production
  username: maji_marriage
  password: <%= ENV["MAJI_MARRIAGE_DATABASE_PASSWORD"] %>
